#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#KEYS JWT
jwt.private.key=${PRIVATE_KEY}
jwt.public.key=${PUBLIC_KEY}

#AWS-S3
cloud.aws.credentials.secret-key=${SECRET_KEY}
cloud.aws.credentials.access-key=${ACCESS_KEY}
cloud.aws.region.static=${REGION_S3}
aws.bucket.name=${BUCKET_S3}