#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#AWS-S3
cloud.aws.credentials.secret-key=${SECRET-KEY}
cloud.aws.credentials.access-key=${ACCESS-KEY}
cloud.aws.region.static=${REGION-S3}
aws.bucket.name=${BUCKET-S3}