spring.config.import=aws-secretsmanager:secret-db-server-jurys,aws-secretsmanager:secrets-jurys-system-app
spring.cloud.aws.region.static=sa-east-1

#DATABASE
spring.datasource.url=jdbc:postgresql://${host}/${dbname}
spring.datasource.username=${username}
spring.datasource.password=${password}

#KEYS JWT
jwt.private.key=${PRIVATE_KEY}
jwt.public.key=${PUBLIC_KEY}

#AWS S3
cloud.aws.region.static=${REGION_S3}
aws.bucket.name=${BUCKET_S3}