#DATABASE -URL
spring.datasource.url=jdbc:postgresql://db-jurys-system.cn0c0ie8qp7x.sa-east-1.rds.amazonaws.com/db_jurys_system

#DATABASE CREDENTIALS
spring.datasource.username=postgres
spring.datasource.password=25012022

#AWS S3
cloud.aws.region.static=${REGION-S3}
aws.bucket.name=${BUCKET-S3}